### ISSUE TITLE
Estudar condição de vitória

### ISSUE THREAD

**Issue by LucasAlive** [Feliperpvieira/arrasa_quarteirao#4]
Possibilidade de condição 1:
-Pontuação fixa, tempo como elemento variável.
Exemplo: Fase com necessidade de alcançar 300 pontos. Se os pontos forem alcançados em...
...1 minuto, ganha 3 ⭐.
...1:30 minutos, ganha 2 ⭐.
...2 minutos, ganha 1 ⭐.
Não alcançar a pontuação em até 2 minutos: derrota.

Possibilidade de condição 2:
-Tempo fixo, pontuação como elemento variável.
Exemplo: Fase com duração de 45 segundos. Se o jogador alcançar....
...900 pontos, ganha 3⭐.
...600 pontos, ganha 2⭐.
...300 pontos, ganha 1⭐.
Não chegar a 300 pontos no tempo: derrota.

**Comment by Feliperpvieira** [comment]
Escolhemos a Possibilidade de condição 1 para estabelecer a vitória.
