### ISSUE TITLE
Esboçar interfaces das telas do jogo

### ISSUE THREAD

**Issue by LucasAlive** [Feliperpvieira/arrasa_quarteirao#5]

**Comment by Feliperpvieira** [comment]
O display de informações dentro das fases foi atualizado. O menu de pausas e a tela de vitória e a de derrota ainda estão desatualizados.
Falta ainda também a tela inicial e os menus de escolha de mundos e de fase.

<table>
  <tr>
    <th>Antes</th>
    <th>Depois</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/47862856/118412385-fdc36c00-b66f-11eb-85fe-d27d5748ed8c.jpg"></td>
    <td><img src="https://user-images.githubusercontent.com/47862856/118412411-2481a280-b670-11eb-98a2-58c2a8641d05.jpg"></td>
  </tr>
</table>
